sudo: required
services:
  - docker
before_install:
  - docker build -t npta/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true npta/react-test npm run test
after_success:
  - docker build -t npta/multi-docker-client ./client
  - docker build -t npta/multi-docker-nginx ./nginx
  - docker build -t npta/multi-docker-server ./server
  - docker build -t npta/multi-docker-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push images to Docker Hub
  - docker push npta/multi-docker-client
  - docker push npta/multi-docker-nginx
  - docker push npta/multi-docker-server
  - docker push npta/multi-docker-worker
